### DeepL Batch Translation (Free API)
POST https://api-free.deepl.com/v2/translate
Content-Type: application/json
Authorization: DeepL-Auth-Key {{DEEPL_API_KEY}}

{
    "text": [
        "Category",
        "Brand",
        "Shipping Time"
    ],
    "formality": "prefer_more",
    "context": "e-commerce",
    "source_lang": "EN",
    "target_lang": "DE"
}
